version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file sam.yaml --s3-bucket rob-umland-build-artifacts --output-template-file output.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml

